/**
 * АВТОГЕНЕРИРОВАНО — scripts/import-incidb.py. Не править вручную.
 *
 * Флаги из INCIDB: для импортированных карточек — комедогенность (Fulton 1989, >= 3),
 * аллергены-отдушки ЕС (Annex III, Регл. 2023/1545), триггеры грибкового акне (эвристика).
 * Для курируемых карточек — только добавление опубликованных данных (комедогенность >= 3,
 * EU-аллергены); feedsMalassezia у курируемых решается вручную в flags.data.ts.
 * В seed.ts эти флаги применяются ПЕРЕД ручными INGREDIENT_FLAGS (ручные побеждают).
 */

export interface IncidbFlags {
  comedogenic?: boolean;
  feedsMalassezia?: boolean;
  fragranceAllergen?: boolean;
}

export const INCIDB_FLAGS: Record<string, IncidbFlags> = {
  "acetyl-cedrene": { fragranceAllergen: true },
  "alpha-isomethyl-ionone": { fragranceAllergen: true },
  "alpha-terpinene": { fragranceAllergen: true },
  "amyl-cinnamal": { fragranceAllergen: true },
  "amyl-salicylate": { fragranceAllergen: true },
  "anethole": { fragranceAllergen: true },
  "arachidic-acid": { feedsMalassezia: true },
  "ascorbyl-palmitate": { feedsMalassezia: true },
  "benzaldehyde": { fragranceAllergen: true },
  "benzyl-benzoate": { fragranceAllergen: true },
  "beta-caryophyllene": { fragranceAllergen: true },
  "c20-40-alkyl-stearate": { feedsMalassezia: true },
  "camphor": { fragranceAllergen: true },
  "cananga-odorata-flower-oil": { fragranceAllergen: true },
  "carvone": { fragranceAllergen: true },
  "cetyl-palmitate": { feedsMalassezia: true },
  "cinnamal": { fragranceAllergen: true },
  "cinnamyl-alcohol": { fragranceAllergen: true },
  "citrus-aurantium-bergamia-peel-oil": { fragranceAllergen: true },
  "citrus-aurantium-dulcis-peel-oil": { fragranceAllergen: true },
  "citrus-aurantium-peel-oil": { fragranceAllergen: true },
  "citrus-limon-peel-oil": { fragranceAllergen: true },
  "dimer-dilinoleyl-dimer-dilinoleate": { feedsMalassezia: true },
  "dimethyl-phenethyl-acetate": { fragranceAllergen: true },
  "ethylhexyl-stearate": { feedsMalassezia: true },
  "eucalyptus-globulus-leaf-oil": { fragranceAllergen: true },
  "eucalyptus-globulus-oil": { fragranceAllergen: true },
  "geranyl-acetate": { fragranceAllergen: true },
  "glyceryl-laurate": { feedsMalassezia: true },
  "glyceryl-oleate": { feedsMalassezia: true },
  "glyceryl-stearate-se": { comedogenic: true },
  "glyceryl-undecylenate": { feedsMalassezia: true },
  "glycol-dilaurate": { feedsMalassezia: true },
  "glycol-distearate": { feedsMalassezia: true },
  "glycol-stearate": { feedsMalassezia: true },
  "hexamethylindanopyran": { fragranceAllergen: true },
  "hexyldecyl-laurate": { feedsMalassezia: true },
  "hydrogenated-vegetable-oil": { comedogenic: true },
  "hydroxycitronellal": { fragranceAllergen: true },
  "isoamyl-laurate": { feedsMalassezia: true },
  "isoeugenol": { fragranceAllergen: true },
  "isopropyl-palmitate": { comedogenic: true, feedsMalassezia: true },
  "jasminum-officinale-oil": { fragranceAllergen: true },
  "juniperus-virginiana-oil": { fragranceAllergen: true },
  "laureth-23": { comedogenic: true },
  "laureth-4": { comedogenic: true },
  "lauric-acid": { comedogenic: true, feedsMalassezia: true },
  "lavandula-angustifolia-oil": { fragranceAllergen: true },
  "lavandula-oil-extract": { fragranceAllergen: true },
  "linalyl-acetate": { fragranceAllergen: true },
  "linolenic-acid": { feedsMalassezia: true },
  "menthol": { fragranceAllergen: true },
  "methyl-salicylate": { fragranceAllergen: true },
  "methylheptyl-isostearate": { feedsMalassezia: true },
  "myristyl-myristate": { comedogenic: true, feedsMalassezia: true },
  "oleic-acid": { feedsMalassezia: true },
  "oleyl-alcohol": { comedogenic: true },
  "peg-100-stearate": { feedsMalassezia: true },
  "peg-150-distearate": { feedsMalassezia: true },
  "peg-20-glyceryl-triisostearate": { feedsMalassezia: true },
  "peg-20-methyl-glucose-sesquistearate": { feedsMalassezia: true },
  "peg-3-distearate": { feedsMalassezia: true },
  "peg-55-propylene-glycol-oleate": { feedsMalassezia: true },
  "peg-8-distearate": { feedsMalassezia: true },
  "peg-8-laurate": { feedsMalassezia: true },
  "peg-8-stearate": { comedogenic: true, feedsMalassezia: true },
  "peg-90-glyceryl-isostearate": { feedsMalassezia: true },
  "peg-ppg-120-10-trimethylolpropane-trioleate": { feedsMalassezia: true },
  "pentaerythrityl-tetraisostearate": { feedsMalassezia: true },
  "phytosteryl-isostearyl-cetyl-stearyl-behenyl-dimer-dilinoleate": { feedsMalassezia: true },
  "pinene": { fragranceAllergen: true },
  "pogostemon-cablin-oil": { fragranceAllergen: true },
  "polyglyceryl-10-dipalmitate": { feedsMalassezia: true },
  "polyglyceryl-2-triisostearate": { feedsMalassezia: true },
  "polyglyceryl-3-diisostearate": { comedogenic: true, feedsMalassezia: true },
  "polyglyceryl-6-distearate": { feedsMalassezia: true },
  "polysorbate-60": { feedsMalassezia: true },
  "polysorbate-80": { feedsMalassezia: true },
  "retinyl-linoleate": { feedsMalassezia: true },
  "rose-ketones": { fragranceAllergen: true },
  "sodium-stearate": { feedsMalassezia: true },
  "sorbitan-isostearate": { feedsMalassezia: true },
  "sorbitan-oleate": { comedogenic: true, feedsMalassezia: true },
  "sorbitan-stearate": { feedsMalassezia: true },
  "sorbitan-tristearate": { feedsMalassezia: true },
  "sucrose-distearate": { feedsMalassezia: true },
  "sucrose-stearate": { feedsMalassezia: true },
  "terpineol": { fragranceAllergen: true },
  "terpinolene": { fragranceAllergen: true },
  "tetramethyl-acetyloctahydronaphthalenes": { fragranceAllergen: true },
  "turpentine": { fragranceAllergen: true },
  "zinc-stearate": { feedsMalassezia: true },

  // обогащение курируемых карточек (только факты, которых нет в flags.data.ts)
  "mentha-piperita-oil": { fragranceAllergen: true },
  "myristic-acid": { comedogenic: true },
};
